version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "12:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 0
    labels:
      - dependencies
    ignore:
      - dependency-name: "@types/node"

