name: check
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  # Our GH actions are expected to be executed by the dependabot in addition to regular executions by Pull Request creators, 
  # and the `GITHUB_TOKEN` env var has a different name in dependabot's secrets (PUBLIC_DEPENDABOT_PACKAGE_TOKEN vs PUBLIC_PACKAGE_GITHUB_TOKEN).
  # To workaround that, we are adding this additional setup job, which outputs the one secret that is present for the current action execution.
  github-token-setup-job:
    runs-on: ubuntu-latest
    outputs:
      github_token: ${{ steps.set-variable.outputs.github_token }}
    steps:
      - uses: actions/checkout@v2
      - name: Set test variable
        id: set-variable
        run: |
          if [ "${{ secrets.PUBLIC_PACKAGE_GITHUB_TOKEN }}" != "" ]; then
            echo "::set-output name=github_token::${{ secrets.PUBLIC_PACKAGE_GITHUB_TOKEN }}"
          elif [ "${{ secrets.PUBLIC_DEPENDABOT_PACKAGE_TOKEN }}" != "" ]; then
            echo "::set-output name=github_token::${{ secrets.PUBLIC_DEPENDABOT_PACKAGE_TOKEN }}"
          fi
        shell: bash

  check:
    runs-on: ubuntu-latest
    needs: [github-token-setup-job]
    env:
      GITHUB_TOKEN: ${{needs.github-token-setup-job.outputs.github_token}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: npm ci
      - run: npm run build
      - uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{secrets.STEDI_ENGINEERING_PUBLIC_REPO_GPG_PRIVATE_KEY}}
          passphrase: ${{secrets.STEDI_ENGINEERING_PUBLIC_REPO_GPG_PASSPHRASE}}
          git-user-signingkey: true
          git-commit-gpgsign: true
        id: import_gpg
      - run: npm run check
