name: check
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: placeholder
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: npm ci
      - run: npm run build
      - uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{secrets.STEDI_ENGINEERING_PUBLIC_REPO_GPG_PRIVATE_KEY}}
          passphrase: ${{secrets.STEDI_ENGINEERING_PUBLIC_REPO_GPG_PASSPHRASE}}
          git-user-signingkey: true
          git-commit-gpgsign: true
        id: import_gpg
      - run: npm run check
