name: check
on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    env:
      GITHUB_TOKEN: placeholder
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: "18"
      - uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: npm ci
      - run: npm run build
      - uses: crazy-max/ghaction-import-gpg@d6f3f49f3345e29369fe57596a3ca8f94c4d2ca7 # v5
        with:
          gpg_private_key: ${{secrets.STEDI_ENGINEERING_PUBLIC_REPO_GPG_PRIVATE_KEY}}
          passphrase: ${{secrets.STEDI_ENGINEERING_PUBLIC_REPO_GPG_PASSPHRASE}}
          git_user_signingkey: true
          git_commit_gpgsign: true
        id: import_gpg
      - run: npm run check

  notify-on-failure-if-dep-update:
    runs-on: ubuntu-latest
    # Always run the action, even if the jobs defined in the `needs` array failed.
    if: ${{ always() }}
    # These needs to be in-sync with the mergify conditions.
    needs: [check]
    steps:
      # 1. Check if the commit originates from a bot.
      # 2. Check if any of the checks failed or were cancelled.

      # contains(fromJson) syntax explained here: https://github.com/orgs/community/discussions/27223#discussioncomment-3255051

      # This repository does not use a reusable workflow we have for this
      # because it is public and public repositories cannot access private workflows.
      - if: |
          contains(fromJson('["opened", "reopened"]'), github.event.action) &&
          github.actor == 'renovate[bot]' &&
          contains(fromJson('["failure", "cancelled"]'), needs.check.outputs.status)
        name: Notify about the failed auto-update
        run: |
          curl "${{ secrets.SLACK_DEPS_CHANNEL_WEBHOOK_URL }}" \
          --data-raw '{"blocks":[{"type":"header","text":{"type":"plain_text","text":":pandagottafixit: Automated dependency update in the ${{github.repository}} failed :pandagottafixit:","emoji":true}},{"type":"section","text":{"type":"mrkdwn","text":"<https://github.com/${{github.repository}}/pull/${{ github.event.pull_request.number }}|${{ github.event.pull_request.title }}>"}}]}' \
          --compressed
