name: check
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: placeholder
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: npm ci
      - run: npm run build
      - uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{secrets.STEDI_ENGINEERING_PUBLIC_REPO_GPG_PRIVATE_KEY}}
          passphrase: ${{secrets.STEDI_ENGINEERING_PUBLIC_REPO_GPG_PASSPHRASE}}
          git-user-signingkey: true
          git-commit-gpgsign: true
        id: import_gpg
      - run: npm run check

  notify-on-dependency-update:
    runs-on: ubuntu-latest
    # Always run the action, even if the jobs defined in the `needs` array failed.
    if: ${{ always() }}
    needs: [check]
    steps:
      - name: Notify about the dependency update
        run: |
          curl "${{ secrets.SLACK_ALERTS_CHANNEL_WEBHOOK_URL }}" \
          --data-raw '{"blocks":[{"type":"header","text":{"type":"plain_text","text":"Automated dependency upgrade in PRETTIER-PLUGIN-JSONATA needs a review","emoji":true}},{"type":"section","text":{"type":"mrkdwn","text":"<https://github.com/Stedi/prettier-plugin-jsonata/pull/${{ github.event.pull_request.number }}|Link to the PR>"}}]}' \
          --compressed
